### ISSUE TITLE
WORDLE: JENGA

### ISSUE THREAD

**Issue by srirajshukla** [pratyushgguptaa/pratyushgguptaa#153]
Just enter a 5 letter word in the title after "WORDLE: " and click "Submit new issue". You don't need to do anything else :D

**Comment by srirajshukla** [comment]
@pratyushgguptaa 😢

**Comment by pratyushgguptaa** [comment]
JENGA is not in the official WORDLE webpage list. And btw what is jenga?
Shall I add the word?

**Comment by srirajshukla** [comment]
Jenga: https://en.wikipedia.org/wiki/Jenga

**Comment by pratyushgguptaa** [comment]
added word [jenga](https://github.com/pratyushgguptaa/pratyushgguptaa/commit/811a40f564a43cf224e6dff1b5f3880888656f57)
